// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        uuid.UUID
	Body      string
	PostedAt  time.Time
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

type Project struct {
	ProjectID   uuid.UUID
	PName       string
	Description string
	OwnerID     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectFile struct {
	FileID       uuid.UUID
	FileLocation pgtype.Text
	FileContent  pgtype.Text
	ProjectID    uuid.UUID
}

type ProjectMetadatum struct {
	ProjectID uuid.UUID
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProjectUser struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

type SystemLog struct {
	LogID     uuid.UUID
	Message   string
	Context   []byte
	CreatedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

type User struct {
	UserID    uuid.UUID
	Token     uuid.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
	LastLogin time.Time
}
