// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role_queries.sql

package plasmadb

import (
	"context"

	"github.com/google/uuid"
)

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE project_users SET role = $1 WHERE project_id = $2 AND user_id = $3
`

type UpdateUserRoleParams struct {
	Role      string
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ProjectID, arg.UserID)
	return err
}
